import { MESSAGE_STATUS, MESSAGE_TYPE } from "@/common";
import { MessageResponse } from "@/interface/response";

export const mockMessages: MessageResponse[] = [
  {
    id: "msg_001",
    conversationId: "conv_001",
    senderId: "eb0b6ca9-b4f3-454a-bc2e-b7db10a91fe5",
    content: "Xin chào bác sĩ",
    type: MESSAGE_TYPE.TEXT,
    status: MESSAGE_STATUS.SENT,
    readBy: ["user_002"],
    createdAt: "2026-05-21T08:00:00Z",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
  {
    id: "msg_002",
    conversationId: "conv_001",
    senderId: "user_002",
    content: "Chào bạn, bạn cần hỗ trợ gì?",
    type: MESSAGE_TYPE.TEXT,
    status: MESSAGE_STATUS.READ,
    readBy: ["user_001"],
    createdAt: "2026-05-21T08:01:00Z",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
  {
    id: "msg_003",
    conversationId: "conv_001",
    senderId: "user_001",
    content: "Tôi bị đau đầu 2 ngày nay",
    type: MESSAGE_TYPE.TEXT,
    status: MESSAGE_STATUS.READ,
    readBy: ["user_002"],
    createdAt: "2026-05-21T08:02:00Z",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
  {
    id: "msg_004",
    conversationId: "conv_002",
    senderId: "user_003",
    content: "Kết quả xét nghiệm đã có chưa?",
    type: MESSAGE_TYPE.TEXT,
    status: MESSAGE_STATUS.DELIVERED,
    readBy: [],
    createdAt: "2026-05-21T08:03:00Z",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
  {
    id: "msg_005",
    conversationId: "conv_002",
    senderId: "user_004",
    content: "Đã có kết quả rồi nhé",
    type: MESSAGE_TYPE.TEXT,
    status: MESSAGE_STATUS.READ,
    readBy: ["user_003"],
    createdAt: "2026-05-21T08:04:00Z",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
    replyTo: "msg_004",
  },
  {
    id: "msg_006",
    conversationId: "conv_003",
    senderId: "user_005",
    content: "Bạn nhớ uống thuốc đúng giờ",
    type: MESSAGE_TYPE.TEXT,
    status: MESSAGE_STATUS.SENT,
    readBy: [],
    createdAt: "2026-05-21T08:05:00Z",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
  {
    id: "msg_007",
    conversationId: "conv_003",
    senderId: "user_006",
    content: "Cảm ơn bác sĩ",
    type: MESSAGE_TYPE.TEXT,
    status: MESSAGE_STATUS.READ,
    readBy: ["user_005"],
    createdAt: "2026-05-21T08:06:00Z",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
  {
    id: "msg_008",
    conversationId: "conv_004",
    senderId: "user_007",
    content: "Lịch hẹn của tôi khi nào vậy?",
    type: MESSAGE_TYPE.TEXT,
    status: MESSAGE_STATUS.DELIVERED,
    readBy: [],
    createdAt: "2026-05-21T08:07:00Z",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
  {
    id: "msg_009",
    conversationId: "conv_004",
    senderId: "user_008",
    content: "9h sáng mai nhé",
    type: MESSAGE_TYPE.TEXT,
    status: MESSAGE_STATUS.READ,
    readBy: ["user_007"],
    createdAt: "2026-05-21T08:08:00Z",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
    replyTo: "msg_008",
  },
  {
    id: "msg_010",
    conversationId: "conv_005",
    senderId: "user_009",
    content: "Bạn có dị ứng thuốc không?",
    type: MESSAGE_TYPE.TEXT,
    status: MESSAGE_STATUS.READ,
    readBy: ["user_010"],
    createdAt: "2026-05-21T08:09:00Z",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
  {
    id: "msg_011",
    conversationId: "conv_005",
    senderId: "user_010",
    content: "Không có dị ứng",
    type: MESSAGE_TYPE.TEXT,
    status: MESSAGE_STATUS.READ,
    readBy: ["user_009"],
    createdAt: "2026-05-21T08:10:00Z",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
  {
    id: "msg_012",
    conversationId: "conv_006",
    senderId: "user_011",
    content: "File kết quả khám đây",
    type: MESSAGE_TYPE.FILE,
    status: MESSAGE_STATUS.SENT,
    readBy: [],
    createdAt: "2026-05-21T08:11:00Z",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
  {
    id: "msg_013",
    conversationId: "conv_006",
    senderId: "user_012",
    content: "Đã nhận được file",
    type: MESSAGE_TYPE.TEXT,
    status: MESSAGE_STATUS.READ,
    readBy: ["user_011"],
    createdAt: "2026-05-21T08:12:00Z",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
    replyTo: "msg_012",
  },
  {
    id: "msg_014",
    conversationId: "conv_007",
    senderId: "user_013",
    content: "Tôi muốn đổi lịch khám",
    type: MESSAGE_TYPE.TEXT,
    status: MESSAGE_STATUS.DELIVERED,
    readBy: [],
    createdAt: "2026-05-21T08:13:00Z",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
  {
    id: "msg_015",
    conversationId: "conv_007",
    senderId: "user_014",
    content: "Bạn muốn đổi sang ngày nào?",
    type: MESSAGE_TYPE.TEXT,
    status: MESSAGE_STATUS.READ,
    readBy: ["user_013"],
    createdAt: "2026-05-21T08:14:00Z",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
  {
    id: "msg_016",
    conversationId: "conv_008",
    senderId: "user_015",
    content: "Tôi bị sốt nhẹ",
    type: MESSAGE_TYPE.TEXT,
    status: MESSAGE_STATUS.SENT,
    readBy: [],
    createdAt: "2026-05-21T08:15:00Z",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
  {
    id: "msg_017",
    conversationId: "conv_008",
    senderId: "user_016",
    content: "Bạn nhớ theo dõi nhiệt độ nhé",
    type: MESSAGE_TYPE.TEXT,
    status: MESSAGE_STATUS.READ,
    readBy: ["user_015"],
    createdAt: "2026-05-21T08:16:00Z",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
  {
    id: "msg_018",
    conversationId: "conv_009",
    senderId: "user_017",
    content: "Ảnh toa thuốc đây",
    type: MESSAGE_TYPE.IMAGE,
    status: MESSAGE_STATUS.READ,
    readBy: ["user_018"],
    createdAt: "2026-05-21T08:17:00Z",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
  {
    id: "msg_019",
    conversationId: "conv_009",
    senderId: "user_018",
    content: "Mình đã xem toa thuốc",
    type: MESSAGE_TYPE.TEXT,
    status: MESSAGE_STATUS.READ,
    readBy: ["user_017"],
    createdAt: "2026-05-21T08:18:00Z",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
    replyTo: "msg_018",
  },
  {
    id: "msg_020",
    conversationId: "conv_010",
    senderId: "user_019",
    content: "Cảm ơn phòng khám rất nhiều",
    type: MESSAGE_TYPE.TEXT,
    status: MESSAGE_STATUS.READ,
    readBy: ["user_020"],
    createdAt: "2026-05-21T08:19:00Z",
    updatedAt: null,
    deletedAt: null,
    deleted: false,
  },
];
